//! gRPC module — tonic service struct, proto includes, and serve_grpc() startup.
//!
//! Phase 27 plan 01: establishes the skeleton so `mnemonic serve` starts both REST and gRPC.
//! Phase 27 plan 02: adds GrpcAuthLayer Tower middleware for async authentication.
//! Phase 28 plan 01: real RPC handler implementations, reflection, and health check wiring.
//!
//! This module is cfg-gated behind the `interface-grpc` feature flag.

pub mod auth;

pub mod proto {
    tonic::include_proto!("mnemonic.v1");
}

/// File descriptor set generated by build.rs for tonic-reflection (HEALTH-02).
/// Enables `grpcurl list` service introspection.
pub const FILE_DESCRIPTOR_SET: &[u8] =
    tonic::include_file_descriptor_set!("mnemonic_descriptor");

use proto::mnemonic_service_server::{MnemonicService, MnemonicServiceServer};

/// Maps ApiError to tonic::Status with matching gRPC status codes (per D-01).
/// Error messages pass through (per D-03).
fn api_error_to_status(e: crate::error::ApiError) -> tonic::Status {
    use crate::error::ApiError;
    match e {
        ApiError::BadRequest(msg) => tonic::Status::invalid_argument(msg),
        ApiError::NotFound => tonic::Status::not_found("not found"),
        ApiError::Forbidden(msg) => tonic::Status::permission_denied(msg),
        ApiError::Unauthorized(msg) => tonic::Status::unauthenticated(msg),
        ApiError::Internal(e) => {
            tracing::error!(error = %e, "gRPC internal error");
            tonic::Status::internal("internal server error")
        }
    }
}

/// Scope enforcement for scoped API keys (duplicated from src/server.rs, per D-06).
/// None auth = open mode (no enforcement). Wildcard key = pass through.
/// Scoped key: mismatch returns Forbidden, missing agent_id forces the key's scope.
fn enforce_scope(
    auth: Option<&crate::auth::AuthContext>,
    requested: Option<&str>,
) -> Result<Option<String>, crate::error::ApiError> {
    match auth {
        None => Ok(None),
        Some(ctx) => match &ctx.allowed_agent_id {
            None => Ok(requested.map(str::to_string)),
            Some(allowed) => match requested {
                None => Ok(Some(allowed.clone())),
                Some(req_id) if req_id == allowed.as_str() => Ok(Some(allowed.clone())),
                Some(req_id) => Err(crate::error::ApiError::Forbidden(format!(
                    "key scoped to {} cannot access {}", allowed, req_id
                ))),
            },
        },
    }
}

/// Converts service-layer Memory to proto Memory message.
/// created_at: parse RFC 3339 string to prost_types::Timestamp via FromStr (per D-09).
/// On parse failure: None (proto optional field sends default) (per D-10).
/// updated_at: not in proto — ignored.
fn memory_to_proto(m: crate::service::Memory) -> proto::Memory {
    let created_at = m.created_at.parse::<prost_types::Timestamp>().ok();
    proto::Memory {
        id: m.id,
        content: m.content,
        agent_id: m.agent_id,
        session_id: m.session_id,
        tags: m.tags,
        created_at,
        embedding_model: m.embedding_model,
    }
}

/// gRPC service struct. Holds the same Arc instances as AppState (per D-11, D-12, D-13).
/// Phase 28 handlers will use these to implement the actual RPCs.
#[derive(Clone)]
pub struct MnemonicGrpcService {
    pub memory_service: std::sync::Arc<crate::service::MemoryService>,
    pub key_service: std::sync::Arc<crate::auth::KeyService>,
    pub compaction_service: std::sync::Arc<crate::compaction::CompactionService>,
    pub backend_name: String,
}

/// Phase 28 RPC handler implementations. All four RPCs delegate to MemoryService
/// with auth context extraction, scope enforcement, input validation, and proto conversion.
#[tonic::async_trait]
impl MnemonicService for MnemonicGrpcService {
    /// StoreMemory — validates content, enforces scope, creates memory, returns proto (GRPC-01).
    async fn store_memory(
        &self,
        request: tonic::Request<proto::StoreMemoryRequest>,
    ) -> Result<tonic::Response<proto::StoreMemoryResponse>, tonic::Status> {
        let auth_ctx = request.extensions().get::<crate::auth::AuthContext>().cloned();
        let body = request.into_inner();

        if body.content.trim().is_empty() {
            return Err(tonic::Status::invalid_argument("content must not be empty"));
        }

        let effective_agent_id = enforce_scope(
            auth_ctx.as_ref(),
            Some(body.agent_id.as_str()).filter(|s| !s.is_empty()),
        )
        .map_err(api_error_to_status)?;

        let memory = self
            .memory_service
            .create_memory(crate::service::CreateMemoryRequest {
                content: body.content,
                agent_id: effective_agent_id
                    .or_else(|| if body.agent_id.is_empty() { None } else { Some(body.agent_id) }),
                session_id: if body.session_id.is_empty() { None } else { Some(body.session_id) },
                tags: if body.tags.is_empty() { None } else { Some(body.tags) },
            })
            .await
            .map_err(api_error_to_status)?;

        Ok(tonic::Response::new(proto::StoreMemoryResponse {
            memory: Some(memory_to_proto(memory)),
        }))
    }

    /// SearchMemories — validates query, enforces scope, searches with embedding, returns ranked results (GRPC-02).
    async fn search_memories(
        &self,
        request: tonic::Request<proto::SearchMemoriesRequest>,
    ) -> Result<tonic::Response<proto::SearchMemoriesResponse>, tonic::Status> {
        let auth_ctx = request.extensions().get::<crate::auth::AuthContext>().cloned();
        let body = request.into_inner();

        if body.query.trim().is_empty() {
            return Err(tonic::Status::invalid_argument("query must not be empty"));
        }

        let effective_agent_id = enforce_scope(
            auth_ctx.as_ref(),
            Some(body.agent_id.as_str()).filter(|s| !s.is_empty()),
        )
        .map_err(api_error_to_status)?;

        let mut params = crate::service::SearchParams {
            q: Some(body.query),
            agent_id: effective_agent_id
                .or_else(|| if body.agent_id.is_empty() { None } else { Some(body.agent_id) }),
            session_id: if body.session_id.is_empty() { None } else { Some(body.session_id) },
            tag: None,
            limit: if body.limit > 0 { Some(body.limit as u32) } else { None },
            threshold: None,
            after: None,
            before: None,
        };
        // Proto repeated tags: pass first tag only (REST SearchParams uses single tag filter).
        if let Some(first_tag) = body.tags.first() {
            params.tag = Some(first_tag.clone());
        }

        let response = self
            .memory_service
            .search_memories(params)
            .await
            .map_err(api_error_to_status)?;

        let results = response
            .memories
            .into_iter()
            .map(|item| proto::SearchResult {
                memory: Some(memory_to_proto(item.memory)),
                distance: item.distance as f32, // f64 -> f32 (proto uses float)
            })
            .collect();

        Ok(tonic::Response::new(proto::SearchMemoriesResponse { results }))
    }

    /// ListMemories — enforces scope, lists with pagination, returns memories + total (GRPC-03).
    async fn list_memories(
        &self,
        request: tonic::Request<proto::ListMemoriesRequest>,
    ) -> Result<tonic::Response<proto::ListMemoriesResponse>, tonic::Status> {
        let auth_ctx = request.extensions().get::<crate::auth::AuthContext>().cloned();
        let body = request.into_inner();

        let effective_agent_id = enforce_scope(
            auth_ctx.as_ref(),
            Some(body.agent_id.as_str()).filter(|s| !s.is_empty()),
        )
        .map_err(api_error_to_status)?;

        let mut params = crate::service::ListParams {
            agent_id: effective_agent_id
                .or_else(|| if body.agent_id.is_empty() { None } else { Some(body.agent_id) }),
            session_id: if body.session_id.is_empty() { None } else { Some(body.session_id) },
            tag: None,
            after: None,
            before: None,
            limit: if body.limit > 0 { Some(body.limit as u32) } else { None },
            offset: if body.offset > 0 { Some(body.offset as u32) } else { None },
        };
        if let Some(first_tag) = body.tags.first() {
            params.tag = Some(first_tag.clone());
        }

        let response = self
            .memory_service
            .list_memories(params)
            .await
            .map_err(api_error_to_status)?;

        let memories = response.memories.into_iter().map(memory_to_proto).collect();

        Ok(tonic::Response::new(proto::ListMemoriesResponse {
            memories,
            total: response.total as i32,
        }))
    }

    /// DeleteMemory — validates id, enforces scope via DB lookup, deletes, returns deleted memory (GRPC-04).
    async fn delete_memory(
        &self,
        request: tonic::Request<proto::DeleteMemoryRequest>,
    ) -> Result<tonic::Response<proto::DeleteMemoryResponse>, tonic::Status> {
        let auth_ctx = request.extensions().get::<crate::auth::AuthContext>().cloned();
        let body = request.into_inner();

        if body.id.is_empty() {
            return Err(tonic::Status::invalid_argument("id must not be empty"));
        }

        // Scope enforcement for scoped keys requires DB lookup (D-08)
        if let Some(ref ctx) = auth_ctx {
            if let Some(ref allowed_id) = ctx.allowed_agent_id {
                match self
                    .memory_service
                    .get_memory_agent_id(&body.id)
                    .await
                    .map_err(api_error_to_status)?
                {
                    None => return Err(tonic::Status::not_found("not found")),
                    Some(ref mem_agent_id) if mem_agent_id != allowed_id => {
                        return Err(tonic::Status::permission_denied(format!(
                            "key scoped to {} cannot access {}",
                            allowed_id, mem_agent_id
                        )));
                    }
                    Some(_) => {} // ownership matches, proceed
                }
            }
        }

        let memory = self
            .memory_service
            .delete_memory(body.id)
            .await
            .map_err(api_error_to_status)?;

        Ok(tonic::Response::new(proto::DeleteMemoryResponse {
            memory: Some(memory_to_proto(memory)),
        }))
    }
}

/// Start the gRPC server on config.grpc_port with tonic-health registered as SERVING.
///
/// Auth layer wraps all services via Server::builder().layer(). GrpcAuthLayer handles
/// health check bypass internally (requests to /grpc.health.v1.Health/* always pass through).
/// Returns anyhow::Result<()> so tokio::try_join! across serve() and serve_grpc() compiles
/// (both futures have the same error type — required by try_join!).
pub async fn serve_grpc(
    config: &crate::config::Config,
    svc: MnemonicGrpcService,
) -> anyhow::Result<()> {
    let addr: std::net::SocketAddr = format!("0.0.0.0:{}", config.grpc_port).parse()?;

    // tonic-health: register MnemonicService as SERVING
    let (health_reporter, health_service) = tonic_health::server::health_reporter();
    health_reporter
        .set_serving::<MnemonicServiceServer<MnemonicGrpcService>>()
        .await;

    // tonic-reflection: build service with the file descriptor set from build.rs (HEALTH-02)
    let reflection_service = tonic_reflection::server::Builder::configure()
        .register_encoded_file_descriptor_set(FILE_DESCRIPTOR_SET)
        .build_v1()
        .expect("failed to build gRPC reflection service");

    tracing::info!(address = %addr, "gRPC server listening");

    tonic::transport::Server::builder()
        .layer(auth::GrpcAuthLayer {
            key_service: std::sync::Arc::clone(&svc.key_service),
        })
        .add_service(health_service)
        .add_service(reflection_service)
        .add_service(MnemonicServiceServer::new(svc))
        .serve(addr)
        .await?;

    Ok(())
}
